DROP TABLE STUDENT_VISITS
IF EXISTS;

DROP TABLE STUDENT
IF EXISTS;

DROP TABLE LESSON
IF EXISTS;


CREATE TABLE STUDENT
(
  ID         INT PRIMARY KEY NOT NULL IDENTITY,
  FIRST_NAME VARCHAR(50)     NOT NULL,
  LAST_NAME  VARCHAR(50)     NOT NULL
);
CREATE UNIQUE INDEX student_id_uindex
  ON STUDENT (ID);


CREATE TABLE LESSON
(
  ID   INT PRIMARY KEY NOT NULL IDENTITY,
  NAME VARCHAR(50)     NOT NULL UNIQUE,
  DATE DATE            NOT NULL
);
CREATE UNIQUE INDEX lesson_id_uindex
  ON LESSON (ID);



CREATE TABLE STUDENT_VISITS
(
  ID         INT PRIMARY KEY NOT NULL IDENTITY,
  STUDENT_ID INT             NOT NULL,
  LESSON_ID  INT             NOT NULL
);
CREATE UNIQUE INDEX student_visits_id_uindex
  ON STUDENT_VISITS (ID);

ALTER TABLE STUDENT_VISITS
  ADD FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (ID);
ALTER TABLE STUDENT_VISITS
  ADD FOREIGN KEY (LESSON_ID) REFERENCES LESSON (ID);
